### ISSUE TITLE
should offer to set up build/test GitHub workflow

### ISSUE THREAD

**Issue by fluffynuts** [fluffynuts/newts#3]
Shouldn't be too hard -- if testing is enabled for the project, include a .github/workflows/ci.yaml with something like:

```
on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Test
      run: |
        npm ci
        npm run build
        npm run lint
        npm test
```

notes:
- perhaps the build / lint / test should be consolidated as a single npm script
- node-version set to 12 for now, but perhaps it should track the version of node used by the person creating the project? At the very least, this would mean no need to re-visit this part of the setup periodically
